// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentRegister.Api.Data;

#nullable disable

namespace StudentRegister.Api.Migrations
{
    [DbContext(typeof(StudentRegisterContext))]
    [Migration("20260916121652_IntialiseDatabase")]
    partial class IntialiseDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentRegister.Api.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Thabo",
                            Gender = "M",
                            LastName = "Mokoena",
                            StudentNumber = "ST001"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Naledi",
                            Gender = "F",
                            LastName = "Dlamini",
                            StudentNumber = "ST002"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Sipho",
                            Gender = "M",
                            LastName = "Ndlovu",
                            StudentNumber = "ST003"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Tracy",
                            Gender = "F",
                            LastName = "Jones",
                            StudentNumber = "ST004"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
